In [1]:
import numpy as np 
from numpy import linalg as LA

In [3]:
A = np.random.rand(3,3)
print(A)

[[0.50470954 0.37727448 0.155525  ]
 [0.44909919 0.06106406 0.39962672]
 [0.74946109 0.6530041  0.83276177]]


In [5]:
A.shape

(3, 3)

In [7]:
LA.det(A)

-0.09565274459371287

In [8]:
invA = LA.inv(A)

In [10]:
print(invA)

[[ 2.19655035  2.22284581 -1.47692547]
 [ 0.77873313 -3.17547475  1.37841592]
 [-2.58746862  0.48952963  1.44913825]]


In [16]:
A.dot(invA)

array([[ 1.00000000e+00,  4.82527280e-17, -2.79936124e-17],
       [ 1.11255293e-16,  1.00000000e+00,  5.78831151e-17],
       [ 4.47070262e-16,  3.23539917e-17,  1.00000000e+00]])

In [14]:
A.dot(invA)

array([[ 1.00000000e+00,  4.82527280e-17, -2.79936124e-17],
       [ 1.11255293e-16,  1.00000000e+00,  5.78831151e-17],
       [ 4.47070262e-16,  3.23539917e-17,  1.00000000e+00]])

In [15]:
LA.svd?

In [17]:
U,D,VT = LA.svd(A)

In [19]:
U.dot(U.T)

array([[ 1.00000000e+00, -2.77850686e-16,  8.45528686e-17],
       [-2.77850686e-16,  1.00000000e+00,  1.79469804e-16],
       [ 8.45528686e-17,  1.79469804e-16,  1.00000000e+00]])

In [20]:
VT.dot(VT.T)

array([[ 1.00000000e+00,  1.57661451e-16, -4.06756516e-17],
       [ 1.57661451e-16,  1.00000000e+00, -1.54094760e-16],
       [-4.06756516e-17, -1.54094760e-16,  1.00000000e+00]])

In [21]:
D.shape

(3,)

In [23]:
A = np.array([[1,0,0],[0,1,0],[0,0,0]])

In [24]:
A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [25]:
b=np.array([0,0,1])

In [28]:
LA.lstsq(A,b)

C:\Users\gokul\AppData\Local\Temp\ipykernel_14268\147288326.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  LA.lstsq(A,b)


(array([0., 0., 0.]), array([], dtype=float64), 2, array([1., 1., 0.]))

In [29]:
LA.det(A)

0.0

In [30]:
LA.pinv(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [31]:
np.trace(A)

2

In [32]:
A = np.random.rand(3,3)

In [33]:
np.trace(A)

1.4837877055125888

In [34]:
np.trace(A.dot(A.T))

2.852548414084702

In [35]:
LA.norm(A,'fro')**2

2.852548414084702

In [37]:
np.trace(A.T.dot(A))

2.852548414084702

In [39]:
a,b=LA.eig(A)

In [40]:
a

array([ 1.49668373, -0.38367373,  0.37077771])

In [41]:
b

array([[-0.63599713, -0.75218595,  0.41465298],
       [-0.37036223, -0.13517137, -0.70761508],
       [-0.67700773,  0.64493798,  0.57213967]])

In [42]:
B = A.T.dot(A)

In [43]:
a,b = LA.eig(B)

In [44]:
a 


array([2.56809725, 0.19297861, 0.09147255])

In [45]:
b

array([[ 0.38935464,  0.90575254, -0.16737773],
       [ 0.65391189, -0.39979185, -0.64231279],
       [ 0.64869269, -0.14063718,  0.74794317]])

In [46]:
a,b = LA.eigh(B)

In [47]:
a

array([0.09147255, 0.19297861, 2.56809725])

In [48]:
b

array([[-0.16737773, -0.90575254, -0.38935464],
       [-0.64231279,  0.39979185, -0.65391189],
       [ 0.74794317,  0.14063718, -0.64869269]])